import type { NextPage } from 'next';
import Head from 'next/head';
import PlaneBoardingSimulation from '@components/PlaneBoardingSimulation/PlaneBoardingSimulation';
import SettingsPanel from '@components/SettingsPanel';
import usePassengerAssets from '@hooks/usePassengerAssets';
import styles from '../styles/Home.module.css';

import useSettings from '@hooks/useSettings';
import Info from '@components/Info';
const Home: NextPage = () => {
  const { planeState, dispatch } = useSettings();
  const { drawAsset } = usePassengerAssets(planeState.size);

  return (
    <main className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta lang='en' />
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}

        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#2d89ef" />
        <meta name="theme-color" content="#ffffff" />


      </Head>

      <Info />
      <PlaneBoardingSimulation planeState={planeState} drawAsset={drawAsset} />
      {/* <PlaneBoardingCanvas dispatch={dispatch} drawAsset={drawAsset} planeState={planeState} /> */}

      <SettingsPanel planeState={planeState} dispatch={dispatch} />


      {/* </PlaneBoardingProvider> */}
    </main>
  )
}

export default Home
